In [ ]:
import pandas as pd
import numpy as np

In [ ]:
## 구글 드라이브에서 파일 mount
from google.colab import drive
drive.mount('/content/drive')
filename = '/content/IMDB-Movie-Data.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
s= pd.Series([3,2,0,1])
s

0    3
1    2
2    0
3    1
dtype: int64

In [ ]:
data = {
    'apple' : [3,2,0,1]
    ,'orange' : [0,3,7,2]
}
p1 = pd.DataFrame(data)
p1

apple  orange
0      3       0
1      2       3
2      0       7
3      1       2

In [ ]:
purchase = pd.DataFrame(data, index = ['June','Robert','Lily','David'])
purchase

apple  orange
June        3       0
Robert      2       3
Lily        0       7
David       1       2

In [ ]:
movies_df = pd.read_csv(filename, index_col="Title")   ## index_col = > index 가 되는 컬럼 설정 
movies_df.head(15)                                       ## 데이터 살펴보기  / parameter에 살펴보기 숫자 

Rank  ... Metascore
Title                                          ...          
Guardians of the Galaxy                     1  ...      76.0
Prometheus                                  2  ...      65.0
Split                                       3  ...      62.0
Sing                                        4  ...      59.0
Suicide Squad                               5  ...      40.0
The Great Wall                              6  ...      42.0
La La Land                                  7  ...      93.0
Mindhorn                                    8  ...      71.0
The Lost City of Z                          9  ...      78.0
Passengers                                 10  ...      41.0
Fantastic Beasts and Where to Find Them    11  ...      66.0
Hidden Figures                             12  ...      74.0
Rogue One                                  13  ...      65.0
Moana                                      14  ...      81.0
Colossal                                   15  ...      70.0

[15 rows x 11 columns]

In [ ]:
#data1 = pd.read_csv(filename)
#data1.head()

Rank                    Title  ... Revenue (Millions) Metascore
0     1  Guardians of the Galaxy  ...             333.13      76.0
1     2               Prometheus  ...             126.46      65.0
2     3                    Split  ...             138.12      62.0
3     4                     Sing  ...             270.32      59.0
4     5            Suicide Squad  ...             325.02      40.0

[5 rows x 12 columns]

In [ ]:
movies_df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Genre               1000 non-null   object 
 2   Description         1000 non-null   object 
 3   Director            1000 non-null   object 
 4   Actors              1000 non-null   object 
 5   Year                1000 non-null   int64  
 6   Runtime (Minutes)   1000 non-null   int64  
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64  
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 133.8+ KB


In [ ]:
df = pd.DataFrame({
    'name' : ['alice', 'bob', 'charlie'],
    'age'  : [25,26,np.nan],
    'state' : ['ak', np.nan, None]
})
df.head()

name   age state
0    alice  25.0    ak
1      bob  26.0   NaN
2  charlie   NaN  None

In [ ]:
print(df['name'].isnull())
print(df['age'].isnull())
print(df['state'].isnull())

0    False
1    False
2    False
Name: name, dtype: bool
0    False
1    False
2     True
Name: age, dtype: bool
0    False
1     True
2     True
Name: state, dtype: bool


In [ ]:
print(df['name'].isnull().sum())
print(df['age'].isnull().sum())
print(df['state'].isnull().sum())

0
1
2


In [ ]:
df2 = pd.DataFrame ({'age': [3, 29],
                   'height': [94,170],
                   'weight': [31,155]})
df2.head()
df2.values
np_array = df2.values
print(np_array)


[[  3  94  31]
 [ 29 170 155]]


In [ ]:
print(np_array.shape)
print(np_array.reshape(1,-1))
print(np_array.reshape(1,-1).shape)

(2, 3)
[[  3  94  31  29 170 155]]
(1, 6)


# ecommerce purchase 실습 


In [ ]:
ecom = pd.read_csv("https://raw.githubusercontent.com/yyoo79/ktech2020winter/main/Ecommerce%20Purchases.txt")
ecom.head()

Address  ... Purchase Price
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  ...          98.14
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  ...          70.73
2                   Unit 0065 Box 5052\nDPO AP 27450  ...           0.95
3              7780 Julia Fords\nNew Stacy, WA 45798  ...          78.04
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  ...          77.82

[5 rows x 14 columns]

In [ ]:
ecom.values

array([['16629 Pace Camp Apt. 448\nAlexisborough, NE 77130-7478',
        '46 in', 'PM', ..., '149.146.147.205', 'el', 98.14],
       ['9374 Jasmine Spurs Suite 508\nSouth John, TN 84355-4179',
        '28 rn', 'PM', ..., '15.160.41.51', 'fr', 70.73],
       ['Unit 0065 Box 5052\nDPO AP 27450', '94 vE', 'PM', ...,
        '132.207.160.22', 'de', 0.95],
       ...,
       ['Unit 4434 Box 6343\nDPO AE 28026-0283', '74 Zh', 'AM', ...,
        '156.210.0.254', 'el', 83.98],
       ['0096 English Rest\nRoystad, IA 12457', '74 cL', 'PM', ...,
        '55.78.26.143', 'es', 38.84],
       ['40674 Barrett Stravenue\nGrimesville, WI 79682', '64 Hr', 'AM',
        ..., '176.119.198.199', 'el', 67.59]], dtype=object)

In [ ]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [ ]:
ecom.head(10)

Address  ... Purchase Price
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  ...          98.14
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  ...          70.73
2                   Unit 0065 Box 5052\nDPO AP 27450  ...           0.95
3              7780 Julia Fords\nNew Stacy, WA 45798  ...          78.04
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  ...          77.82
5  7502 Powell Mission Apt. 768\nTravisland, VA 3...  ...          25.15
6     93971 Conway Causeway\nAndersonburgh, AZ 75107  ...          88.56
7  260 Rachel Plains Suite 366\nCastroberg, WV 24...  ...          44.25
8            2129 Dylan Burg\nNew Michelle, ME 28650  ...          59.54
9    3795 Dawson Extensions\nLake Tinafort, ID 88739  ...          95.63

[10 rows x 14 columns]

In [ ]:
ecom['Purchase Price'].mean()       # 평균가격 

50.34730200000025

In [ ]:
round(ecom['Purchase Price'].mean(),1)  # 소수 1번째 자리까지 반올림 

50.3

In [ ]:
round(ecom['Purchase Price'].max(),1)   # 최대값 

100.0

In [ ]:
round(ecom['Purchase Price'].min(),1)   # 최대값 

0.0

In [ ]:
ecom[ecom['Language'] == 'en']['Credit Card'].count()

1098

In [ ]:
ecom['Job'].value_counts().head(5) # Job 컬럼 value당 counts

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Designer, jewellery                  27
Research officer, political party    27
Name: Job, dtype: int64

In [ ]:
ecom['Job'].value_counts(sort = True, ascending = True).head() # 결과값 오름차순 정렬 

Information systems manager    5
Investment analyst             5
Editor, film/video             6
Actuary                        6
Music therapist                7
Name: Job, dtype: int64

In [ ]:
ecom[ecom['Lot'] == '90 WT']['Purchase Price']    # 90 WT 지역에서 구매된 거래 금액

513    75.1
Name: Purchase Price, dtype: float64

In [ ]:
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [ ]:
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95.0)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

*.apply() & Lambda*



In [ ]:
# 만료연도가 25인 것만 추출하기
ecom[ecom['CC Exp Date'].apply(lambda x: x[3:]) == '25'].head(5)

Address  ... Purchase Price
4   23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  ...          77.82
5   7502 Powell Mission Apt. 768\nTravisland, VA 3...  ...          25.15
7   260 Rachel Plains Suite 366\nCastroberg, WV 24...  ...          44.25
13  118 Melton Via Suite 681\nAlexanderbury, FL 32104  ...           8.93
15     31730 Chelsea Crest\nBlakemouth, CT 90395-0620  ...          71.78

[5 rows x 14 columns]

In [ ]:
# 끝자리 25인지 확인 
sum(ecom['CC Exp Date'].apply(lambda x: x[3:] == '25'))


1033

In [ ]:
# 가장 인기있는 이메일 제공자/호스트(eg gmail.com, yahoo.com)찾아내기 

#email컬럼값 살펴보기 

ecom['Email'].head(5)


0                 pdunlap@yahoo.com
1                anthony41@reed.com
2    amymiller@morales-harrison.com
3       brent16@olson-robinson.info
4       christopherwright@gmail.com
Name: Email, dtype: object

In [ ]:
# 샘플 데이터 1개를 가지고 데이터 파싱 연습하기
 
example_email = ecom['Email'].iloc[0]
example_email

'pdunlap@yahoo.com'

In [ ]:
#'@' 문자를 기준으로 컬럼값 나누기 

example_email.split('@')

['pdunlap', 'yahoo.com']

In [ ]:
# 나눈 컬럼값 2번째 값 불러오기 
example_email.split('@')[1]

'yahoo.com'